var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var strArrr;
var numArr;
var numArrr;
var boolArr;
var boolArrr;
var strNumTuple;
myVar = [];
myBool = true;
myNum = -5;
myString = "hellllo".slice(3);
strArr = ["hey", "what", "okay"];
numArr = [1, 2, 4];
boolArr = [true, false, true];
strNumTuple = ["hasdasd", 5];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(myUndefined);
